```{r}
plot.exp<-function(e,g,c){
  g<-g
  d<-data.frame(exp=e,group=g)
  p<-ggplot(d,aes(group,exp))+
    geom_boxplot(outlier.size = 0)+
    geom_jitter(position=position_jitter(width=0.2),aes(factor(group), exp,colour=group)) +
    scale_color_manual("",values=c)+
    theme_bw()
  return(p)
}

mir<-c("hsa-miR-34c-5p","hsa-miR-34b-5p")

for (m in mir){
 data<-assay(rld)
 g<-design$condition
 print(plot.mir(data[m,],m,g,c("red3","SlateBlue3"))+labs(title=m))
 
}

```


```{r}
counts<-read.table("data/clusters/seqcluster/res/ann.tab",sep="\t",header=T,row.names=1)
ann<-counts[,2]
names(ann)<-row.names(counts)
counts<-counts[,2:(ncol(counts)-1)]

sv<-read.table("data/clusters/svrna.txt",sep="\t",header=T)
exp<-matrix(colSums(sv[,3:30]),nrow=1)
colnames(exp)<-names(counts)
rownames(exp)<-"svrna"
```

Add the svRNA to all clusters

```{r}
counts<-rbind(exp,counts)
design<-data.frame(condition=substr(names(counts),1,2))
row.names(design)<-names(counts)

dds <- DESeqDataSetFromMatrix(countData = counts,
                              colData = design,
                              design = ~ condition)
dds <- estimateSizeFactors( dds )
rld <- rlogTransformation(dds,blind=TRUE)
```

Plot tendency

```{r}
print(plot.exp(assay(rld)[1,],design$condition,c("red3","SlateBlue3","red3","SlateBlue3"))
      +labs(title="svRNA") )

```

