---
title: "compare_trna_counts.rmd"
author: "Lorena Pantano"
date: "08/15/2014"
output: html_document
---


```{r setup}
library(knitr)
library(rmarkdown)
library(knitrBootstrap)
library(ggplot2)
library(reshape)
library(plyr)
library(edgeR)
library(CHBUtils)
library(devtools)
library(DESeq2)
library(qvalue)
library("RColorBrewer")
devtools::load_all("~/repos/isomiRs")
opts_chunk$set(tidy=TRUE, highlight=T, figalign="center",
 fig.height=6, fig.width=6, message=F, error=F, warning=F, bootstrap.show.code=FALSE)
```


```{r load-seqcluster}
sc_tab <- read.table("work/define.cluster.Dec/res/ann.tab",sep="\t",header=T)
head(sc_tab)
```

```{r load-srnabench}
list.dirs <- function(path=".", pattern=NULL, all.dirs=FALSE,
  full.names=FALSE, ignore.case=FALSE)
{
  all <- list.files(path, pattern, all.dirs,
                    full.names, recursive=FALSE, ignore.case)
  all[file.info(dir(path,full.names=T))$isdir]
}

get_counts <- function(col)
{
    bench_tab <- data.frame(name="1")
    for (f in list.dirs("miranalyzer_output_trimmed/")){
        print(f)
        c<-read.table(paste0("miranalyzer_output_trimmed/",f,"/out/hg19-tRNAs_sense.grouped"),header=T,sep="\t")
        names(c)[col]<-f
        bench_tab<-merge(bench_tab,c[,c(1,col)],by=1,all=T)
        }
    bench_tab <- bench_tab[2:nrow(bench_tab),]
    row.names(bench_tab)<-bench_tab$name
    bench_tab<-bench_tab[,2:ncol(bench_tab)]
    bench_tab[is.na(bench_tab)] <- 0
    bench_tab
}
unique <- get_counts(2)
multi <- get_counts(3)

samples = c("cc1","cc2","cc3","cc4","cc5","cc6","cc7",
            "ct1","ct2","ct3","ct4","ct5","ct6","ct7",
            "pc1","pc2","pc3","pc4","pc5","pc6","pc7",
            "pt1","pt2","pt3","pt4","pt5","pt6","pt7")
get_counts_mirna <- function(col)
{
    bench_tab <- data.frame()
    for (f in samples){
        print(f)
        c<-read.table(paste0("miranalyzer_output_trimmed/",f,"/out/miRBase_isoAnnotation.txt"),header=T,sep="\t",comment.char = "/")
        #print(head(c))
        c$sample = f
        names(c)[col] = "counts"
        c$read = as.character(c$read)
        bench_tab = rbind(bench_tab,c[c[,col]>2,c(1,col,ncol(c))])
        }
    #print(head(bench_tab))
    bench_tab = reshape(bench_tab,timevar="sample", idvar = "read", direction = "wide")
    bench_tab = bench_tab[,2:ncol(bench_tab)]
    #print(head(bench_tab))
    bench_tab[is.na(bench_tab)] = 0
    bench_tab
    
}

iso <- get_counts_mirna(6)
names(iso) = sub("counts.","",names(iso))

```


```{r counts}

sc_counts<-sc_tab
sc_counts<-sc_counts[,3:(3+27)]
sc_counts<-sc_counts[,sort(names(sc_counts))]

get_size_factor<-function(counts, cols)
{
    counts <- counts[,cols]
    counts<-counts[rowSums(counts==0)<5,]
    d<-data.frame(g=gsub("[0-9]+","",names(counts)), b=1)
    row.names(d)<-names(counts)
    dse <- DESeqDataSetFromMatrix(countData = counts, 
                                     colData = d, design = ~g)
    dse<-estimateSizeFactors(dse)
    sizeFactors(dse)
}


rlog_counts<-function(counts, cols, size)
{
    counts <- counts[,cols]
    counts<-counts[rowSums(counts==0)<5,]
    d<-data.frame(g=gsub("[0-9]+","",names(counts)), b=1)
    row.names(d)<-names(counts)
    dse <- DESeqDataSetFromMatrix(countData = counts, 
                                  colData = d, design = ~g)
    sizeFactors(dse) <- size
    rlogTransformation(dse)
}

cc_size <- get_size_factor(sc_counts, 1:14)
pc_size <- get_size_factor(sc_counts, 15:28)
cc_trna_unique_rlog <- rlog_counts(unique, 1:14, cc_size)
pc_trna_unique_rlog <- rlog_counts(unique, 15:28, pc_size)
cc_trna_multi_rlog <- rlog_counts(multi, 1:14, cc_size)
pc_trna_multi_rlog <- rlog_counts(multi, 15:28, pc_size)
write.table(assay(cc_trna_unique_rlog),"miranalyzer_output_trimmed/trna-counts-uniq-cc.tsv",sep="\t")
write.table(assay(pc_trna_unique_rlog),"miranalyzer_output_trimmed/trna-counts-uniq-pc.tsv",sep="\t")
write.table(assay(cc_trna_multi_rlog),"miranalyzer_output_trimmed/trna-counts-multi-cc.tsv",sep="\t")
write.table(assay(pc_trna_multi_rlog),"miranalyzer_output_trimmed/trna-counts-multi-pc.tsv",sep="\t")

```

# PLS-DA

```{r plsda-bench}
counts<-setClass("DataSeq",
slots=c(counts="matrix",
normcounts="matrix",
design="data.frame"
))


do_pls<-function(counts)
{
    obj<-counts()
    obj@normcounts<-as.matrix(assay(counts))
    obj@design<-data.frame(g=gsub("[0-9]+","",colnames(obj@normcounts)), b=1)
    pls <- isoPLSDA(obj,"g",nperm = 400)    
    pls
}
cc_bench_unique <- do_pls(cc_trna_unique_rlog)
cc_bench_multi <- do_pls(cc_trna_multi_rlog)
pc_bench_unique <- do_pls(pc_trna_unique_rlog)
pc_bench_multi <- do_pls(pc_trna_multi_rlog)

#isoPLSDAplot(pls$components, groups = d$g)


```


```{r plsda-seqcluster}
counts<-setClass("DataSeq",
slots=c(counts="matrix",
normcounts="matrix",
design="data.frame"
))


sc_trna<-subset(sc_tab, grepl("tRNA",ann))
sc_trna<-sc_trna[,3:ncol(sc_trna)]
sc_trna<-sc_trna[,sort(names(sc_trna))]
sc_cc_trna_unique_rlog <- rlog_counts(sc_trna, 1:14, cc_size)
sc_pc_trna_unique_rlog <- rlog_counts(sc_trna, 15:28, pc_size)

sc_pls_cc <- do_pls(sc_cc_trna_unique_rlog)
sc_pls_pc <- do_pls(sc_pc_trna_unique_rlog)

isoPLSDAplot(sc_pls_pc$components, groups = d$g)
```


# DE

```{r accuracy}
get_accuracy<-function(hr,c,t){
  clus<-cutree(hr,2)
  g1<-names(clus[clus==1])
  ng1.cc<-sum(sub("[0-9]","",(g1))== c )
  ng1.ct<-sum(sub("[0-9]","",(g1))== t )
  ng1<-(max(ng1.cc,ng1.ct))/length(g1)
  g2<-names(clus[clus==2])
  ng2.cc<-sum(sub("[0-9]","",(g2))== c )
  ng2.ct<-sum(sub("[0-9]","",(g2))== t )
  ng2<-(max(ng2.cc,ng2.ct))/length(g2)
  a<-min(ng1,ng2)
  return(a)
}

```


```{r deseq-functions}
#########################################################
#con<-"cc"
#treat<-"ct"
#ini<-1
#end<-14
#name<-"multi_bench"


do_de_heatmap = function(table,ini,end,con,treat,name){
    design<-data.frame(condition=c(rep(con,7),rep(treat,7)))
    row.names(design)<-names(table)[ini:end]
    
    mirna<-table[ini:end]
    mirna<-mirna[apply(mirna>10,1,sum)>=5,]
    mirna<-mirna[!is.na(mirna[,1]),]
    
    #write.table(row.names(mirna),"tables.res/ids.ccvsct.filter.txt",row.names=F,quote=F,col.names=F)
    
    dds <- DESeqDataSetFromMatrix(countData = mirna,
                                  colData = design,
                                  design = ~ condition)
    dds <- estimateSizeFactors( dds )
    #save(dds,file=paste(treat,"vs",con,".dss",sep="\t"))
    
    dds<-DESeq(dds)
    
    res<-results(dds,independentFiltering=FALSE)
    res.all<-mcols(dds,use.names=TRUE)
    res.dt<-as.data.frame(res)
    res.dt<-res.dt[!is.na(res.dt$padj),]
    #pdf(paste("heatmap.res/",unique(design[,1])[2],"vs",unique(design[,1])[1],sep="",
    #          ".pvalue.clu.pdf"))
    #hist(res.dt$pvalue,main="pvalue distribution")
    #dev.off()
    
    #head(res.dt[order(res.dt$pvalue),],13)
    #q<-qvalue(res.dt$pvalue[!is.na(res.dt$pvalue)],
    #          fdr.level=0.3)
    #summary(q)
    rld <- rlogTransformation(dds, blind=TRUE)
    #save(rld,file=paste(treat,"vs",con,".rld",sep="\t"))
    
    idx.lim<-max(which(sort(res.dt$pvalue)<0.06))
    hmcol<- colorRampPalette(brewer.pal(9,"YlGnBu"))(256)
    max.acc<-0
    for (lim in seq(10,idx.lim,5)){
        select<-row.names((res.dt[order(res.dt$pvalue),])[1:lim,])
        cor_t <- 1 - cor((assay(rld)[select,]))
        hr<-hclust(as.dist(cor_t),method="ward.D2")
        cor_tc <- 1 - cor(t((assay(rld)[select,])))
        hc<-hclust(as.dist(cor_tc),method="ward.D2")
        par(mar=c(3,5,5,2),cex=.5)
        #pdf(paste("heatmap.res/",unique(design[,1])[2],"vs",unique(design[,1])[1],sep="",
        #          ".top",lim,".",name,".pdf"))
        #p<-heatmap.2(assay(rld)[select,], col = hmcol,
        #          Colv=as.dendrogram(hr), Rowv=as.dendrogram(hc),
        #          scale="row",
        #          dendrogram="col", trace="none",cexRow=.7,
        #          ColSideColors=c(rep("gray",7),rep("yellow",7)),
        #          ,margins=c(7,7),keysize=1.5,main=paste("top: ",lim))
        #dev.off()
        acc<-get_accuracy(hr,con,treat)
        if (acc>=max.acc){
            max.heatmap<-lim
            max.acc<-acc
            }
        }
    
    #write.table(cbind(res.dt,assay(rld)[row.names(res.dt),],ann[row.names(res.dt)]),paste("tables.res/DEseq.",name,".",unique(design[,1])[2],"vs",unique(design[,1])[1],sep="",".txt"),quote=F,sep="\t")
    realvalue<-max.acc
    return (list(acc=realvalue,res=res.dt,max=max.heatmap,log=rld))
}


do_permutation = function(realvalue, max.heatmap, res.dt, rld, con, treat, name){
    #permutation of micros but same DE: 22 87%
    acc<-vector()
    for (perm in 1:400){
        select<-row.names((res.dt[sample(1:nrow(res.dt),max.heatmap),])[1:max.heatmap,])  
        cor_t <- 1 - cor((assay(rld)[select,]))
        hr<-hclust(as.dist(cor_t),method="ward.D2")
        acc<-c(get_accuracy(hr,con,treat),acc)
        }
    pval=sum(acc>=realvalue)/401
    d<-density(acc,bw=0.1)
    png(paste("miranalyzer/",name,treat,"vs",con,sep="",
              ".signif.random.",name,".png"))
    plot(d, main="density random score",xlab="clustering scores",xlim=c(0,1.1))
    polygon(d, col="steelblue", border="blue")
    abline(v=realvalue,col="red",lwd=2)
    text(1,3,labels=paste("p-value:",round(pval,digits=2)),cex=0.7)
    dev.off()
    
}

```

## tRNA

```{r deg_bench_comp}
deg_res = do_de_heatmap(multi,1,14,"cc","ct","multi_ct")
do_permutation(deg_res[["acc"]], deg_res[["max"]], deg_res[["res"]],deg_res[["log"]],"cc","ct","multi_")


deg_res = do_de_heatmap(multi,15,28,"pc","pt","multi_pt")
do_permutation(deg_res[["acc"]], deg_res[["max"]], deg_res[["res"]],deg_res[["log"]],"pc","pt","multi_")


deg_res = do_de_heatmap(unique,1,14,"cc","ct","unique_ct")
do_permutation(deg_res[["acc"]], deg_res[["max"]], deg_res[["res"]],deg_res[["log"]],"cc","ct","uniqeu_")

deg_res = do_de_heatmap(unique,15,28,"pc","pt","unique_pt")
do_permutation(deg_res[["acc"]], deg_res[["max"]], deg_res[["res"]],deg_res[["log"]],"pc","pt","unique_")

```


## isomiRs

```{r deg_bench_comp_isomirs}
deg_res = do_de_heatmap(iso,1,14,"cc","ct","isomirs")
do_permutation(deg_res[["acc"]], deg_res[["max"]], deg_res[["res"]],deg_res[["log"]],"cc","ct","isomirs_")

deg_res = do_de_heatmap(iso,15,28,"pc","pt","isomirs")
do_permutation(deg_res[["acc"]], deg_res[["max"]], deg_res[["res"]],deg_res[["log"]],"pc","pt","isomirs_")

```

